version: '3'

volumes:
  jenkins-docker-certs:
    name: jenkins-docker-certs
  jenkins-data:
    name: jenkins-data
  maven-cache:
    name: maven-cache
  oracle-tns-admin:
    name: oracle-tns-admin
  oracle-wallet:
    name: oracle-wallet
  
networks:
  jenkins:
    name: jenkins
    external: true

services:
  jenkins-docker:
    container_name: jenkins_docker
    image: docker:dind
    privileged: true
    ports:
     - 2376:2376
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    command: --storage-driver=overlay2
  jenkins-controller:
    container_name: jenkins_controller
    build: jenkins-controller
    ports:
      - 50000:50000
      - 8080:8080
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
    depends_on:
      - jenkins-docker
  jenkins-agent:
    container_name: jenkins_agent
    build: jenkins-agent
    ports:
      - 22:22
    networks:
      - jenkins
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=$JENKINS_AGENT_SSH_PUBKEY
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - TNS_ADMIN=/opt/oracle/network/admin
    volumes:
      - maven-cache:/var/jenkins_home/.m2
      - oracle-tns-admin:/opt/oracle/network/admin
      - oracle-wallet:/opt/oracle/wallet
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - jenkins-docker
