version: '3.8'

volumes:
  jenkins-data:
    name: jenkins-data

services:
  # See https://davelms.medium.com/run-jenkins-in-a-docker-container-part-2-socat-d5f18820fe1d
  jenkins-docker:
    container_name: jenkins_docker
    image: alpine/socat
    restart: unless-stopped
    hostname: jenkins-docker
    expose:
      - "2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
  dns-proxy-server:
    container_name: dns_proxy_server
    image: defreitas/dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    hostname: dns.mageddo
