version: '3.8'

networks:
  jenkins-network:
    name: jenkins
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

services:
  jenkins-nfs-server:
    container_name: jenkins_nfs_server
    build: jenkins-nfs-server
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    environment:
      - NFS_LOG_LEVEL=DEBUG
      - NFS_DISABLE_VERSION_3=1
    hostname: jenkins-nfs-server
    networks:
      jenkins-network:
        ipv4_address: 192.168.1.3
    volumes:
    - type: volume
      source: nfs-server-volume
      target: /nfs
    - type: bind
      source: ${LIB_MODULES_DIR}
      target: /lib/modules
      read_only: true
