version: '3.8'

networks:
  jenkins-network:
    name: jenkins
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

volumes:
  jenkins-agent-workspace:
    name: jenkins-agent-workspace
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.3,nfsvers=4,nolock,soft,rw"
      device: ":/workspace"
  jenkins-m2-repository:
    name: jenkins-m2-repository
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.3,nfsvers=4,nolock,soft,rw"
      device: ":/repository"
     
services:
  jenkins-nfs-client:
    container_name: jenkins_nfs_client
    image: ghcr.io/paulissoft/pato-jenkins-agent:latest
#    image: jenkins/inbound-agent:latest
    command: sleep infinity
    hostname: jenkins-nfs-client
    networks:
      - jenkins-network
    volumes:
      - jenkins-m2-repository:/home/jenkins:rw
    volumes:
    - type: volume
      source: jenkins-agent-workspace
      target: /home/jenkins/agent/workspace
      volume:
        nocopy: true
    - type: volume
      source: jenkins-m2-repository
      target: /home/jenkins/.m2/repository
      volume:
        nocopy: true

      
