version: '3.8'

networks:
  jenkins-network:
    name: jenkins
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

volumes:
  jenkins-data:
    name: jenkins-data

services:
  jenkins-controller:
    container_name: jenkins_controller
    build: jenkins-controller
    restart: unless-stopped
    hostname: jenkins-controller
    ports:
      - 50000:50000
      - 8080:8080
    networks:
      jenkins-network:
        ipv4_address: 192.168.1.4
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://192.168.1.2:2375
      - DOCKER_TLS_VERIFY=""
    depends_on:
      - jenkins-docker
