version: '3.8'

networks:
  jenkins-network:
    name: jenkins

volumes:
  jenkins-agent-home:
    name: jenkins-agent-home
    driver_opts:
      type: "nfs"
      o: "addr=${JENKINS_NFS_SERVER:-host.docker.internal},nfsvers=4,nolock,soft,rw"
      device: ":"

services:
  jenkins-nfs-client:
    container_name: jenkins_nfs_client
    image: ghcr.io/paulissoft/pato-jenkins-agent:latest
    hostname: jenkins-nfs-client
    networks:
      - jenkins-network
    volumes:
      - jenkins-agent-home:/home/jenkins:rw

