version: '3.8'

networks:
  jenkins-network:
    name: jenkins
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

volumes:
  jenkins-data:
    name: jenkins-data
  nfs-server-volume:
    name: nfs-server-volume
  jenkins-agent-workspace:
    name: jenkins-agent-workspace
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.3,nfsvers=4,nolock,soft,rw"
      device: ":/workspace"
  jenkins-m2-repository:
    name: jenkins-m2-repository
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.3,nfsvers=4,nolock,soft,rw"
      device: ":/repository"

services:
  # See https://davelms.medium.com/run-jenkins-in-a-docker-container-part-2-socat-d5f18820fe1d
  jenkins-docker:
    profiles:
      - docker
      - controller
    container_name: jenkins_docker
    image: alpine/socat
    restart: unless-stopped
    hostname: jenkins-docker
    networks:
      jenkins-network:
        ipv4_address: 192.168.1.2
    expose:
      - "2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
  jenkins-nfs-server:
    profiles:
      - nfs
    container_name: jenkins_nfs_server
    build: jenkins-nfs-server
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    hostname: jenkins-nfs-server
    networks:
      jenkins-network:
        ipv4_address: 192.168.1.3
    volumes:
    - type: ${NFS_SERVER_VOLUME_TYPE:-volume}
      source: ${NFS_SERVER_VOLUME:-nfs-server-volume}
      target: /nfs
    - type: bind
      source: ${LIB_MODULES_DIR:-/lib/modules}
      target: /lib/modules
      read_only: true
    environment:
      - NFS_LOG_LEVEL=DEBUG
      - NFS_DISABLE_VERSION_3=1
  jenkins-controller:
    profiles:
      - controller
    container_name: jenkins_controller
    build: jenkins-controller
    restart: unless-stopped
    hostname: jenkins-controller
    ports:
      - 50000:50000
      - 8080:8080
    networks:
      jenkins-network:
        ipv4_address: 192.168.1.5
    volumes:
      - jenkins-data:/var/jenkins_home
      - ${JENKINS_SSH_PRIVATE_KEY:-~/.ssh/id_rsa}:/var/jenkins_home/.ssh/${JENKINS_SSH_PRIVATE_KEY_BASE:-id_rsa}
    environment:
      - DOCKER_HOST=tcp://192.168.1.2:2375
      - DOCKER_TLS_VERIFY=""
    depends_on:
      - jenkins-docker
  # Just a sidekick that will create two NFS client volumes.
  jenkins-create-nfs-volumes:
    profiles:
      - nfs
    container_name: jenkins_create_nfs_volumes
    image: "ghcr.io/paulissoft/pato-jenkins-agent:latest"
    restart: "no"
    networks:
      - jenkins-network
    volumes:
    - type: volume
      source: jenkins-agent-workspace
      target: /home/jenkins/agent/workspace
      volume:
        nocopy: true
    - type: volume
      source: jenkins-m2-repository
      target: /home/jenkins/.m2/repository
      volume:
        nocopy: true
    command:
      - /bin/sh
      - -c
      - |
        set -x
        find /home/jenkins/agent/workspace /home/jenkins/.m2/repository
    depends_on:
      - jenkins-nfs-server
