version: '3.8'

networks:
  jenkins-network:
    name: jenkins

volumes:
  jenkins-data:
    name: jenkins-data

services:
  # See https://davelms.medium.com/run-jenkins-in-a-docker-container-part-2-socat-d5f18820fe1d
  jenkins-docker:
    container_name: jenkins_docker
    image: alpine/socat
    restart: unless-stopped
    networks:
      jenkins-network:
        aliases:
          - jenkins-docker
    expose:
      - "2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
  jenkins-controller:
    container_name: jenkins_controller
    build: jenkins-controller
    restart: unless-stopped
    ports:
      - 50000:50000
      - 8080:8080
    networks:
      - jenkins-network
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://jenkins-docker:2375
      - DOCKER_TLS_VERIFY=""
    depends_on:
      - jenkins-docker
