version: '3.8'

networks:
  jenkins-network:
    name: jenkins

volumes:
  jenkins-m2-repository:
    name: jenkins-m2-repository
    driver_opts:
      type: "nfs"
      o: "addr=${JENKINS_NFS_SERVER},nfsvers=4,nolock,soft,rw"
      device: ":"

services:
  jenkins-nfs-client-m2-repository:
    container_name: jenkins_nfs_client_m2_repository
    image: ghcr.io/paulissoft/pato-jenkins-agent:latest
    hostname: jenkins-nfs-client-m2-repository
    networks:
      - jenkins-network
    volumes:
      - jenkins-m2-repository:/home/jenkins:rw
  jenkins-nfs-client-agent-workspace:
    container_name: jenkins_nfs_client_agent_workspace
    image: ghcr.io/paulissoft/pato-jenkins-agent:latest
    hostname: jenkins-nfs-client-agent-workspace
    networks:
      - jenkins-network
    volumes:
      - jenkins-agent-workspace:/home/jenkins:rw

