# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Oracle Tools web site
email: paulissoft@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site describes the Oracle Tools suite designed to help you to build your
  Oracle database application quick but NOT dirty.
baseurl: "/oracle-tools" # the subpath of your site, e.g. /blog
url: "https://paulissoft.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  paulissoft
highlighter: rouge
encoding: utf-8
destination: _site
lang: 'en'             # The language setting is used in /includes/header.html for html-settings
locale: 'en'
minimal_mistakes_skin: "aqua" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Build settings
# theme: minima

# Build settings
markdown             : kramdown
# Outputting
permalink            : /:categories/:title/
paginate             : 5 # amount of posts to show
paginate_path        : /page:num/
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone             : CET

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#      ______                           ______          __          __
#     / ____/__  ____ ___       __     / ____/  _______/ /_  ______/ /__  _____
#    / / __/ _ \/ __ `__ \   __/ /_   / __/ | |/_/ ___/ / / / / __  / _ \/ ___/
#   / /_/ /  __/ / / / / /  /_  __/  / /____>  </ /__/ / /_/ / /_/ /  __(__  )
#   \____/\___/_/ /_/ /_/    /_/    /_____/_/|_|\___/_/\__,_/\__,_/\___/____/
#
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - webrick
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme


#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: false
      share: true
      related: true
      sitemap: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false
      sitemap: true

comments:
  provider: "custom"
  
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Frontpage-Layout-Settings
excerpt_separator: <!--more-->   # Use <!--more--> in your posts to generate an excerpt and a teaser

#
# Minimal mistakes settings
#
# 
#     __  ____       _                 __   __  ____      __        __                _____      __  __  _                 
#    /  |/  (_)___  (_)___ ___  ____ _/ /  /  |/  (_)____/ /_____ _/ /_____  _____   / ___/___  / /_/ /_(_)___  ____ ______
#   / /|_/ / / __ \/ / __ `__ \/ __ `/ /  / /|_/ / / ___/ __/ __ `/ //_/ _ \/ ___/   \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#  / /  / / / / / / / / / / / / /_/ / /  / /  / / (__  ) /_/ /_/ / ,< /  __(__  )   ___/ /  __/ /_/ /_/ / / / / /_/ (__  ) 
# /_/  /_/_/_/ /_/_/_/ /_/ /_/\__,_/_/  /_/  /_/_/____/\__/\__,_/_/|_|\___/____/   /____/\___/\__/\__/_/_/ /_/\__, /____/  
#                                                                                                            /____/        
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme         : "mmistakes/minimal-mistakes@4.22.0"
search               : true

# GJP 2021-02-09 To prevent this warning:
#
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
github: [metadata]
