name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          # see <distributionManagement> in pom.xml
          server-id: github-paulissoft
          java-version: '11'
          distribution: 'temurin'
      - name: Publish package in root
        run: mvn --batch-mode -N deploy
      - name: Publish package in jdbc directory
        run: mvn --batch-mode -f jdbc/pom.xml deploy
