name: Deploy Docker image pato-jenkins-agent

on:
  push:
    branches:
      - 'main'
      - 'build/*'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ env.REGISTRY }}/paulissoft/pato-jenkins-agent
  CONTEXT: ./jenkins/jenkins-agent

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Build and Push Versioned Docker Image
        id: build-and-push
        uses: docker/build-push-action@v2
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          context: ${{ env.CONTEXT }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and Push Latest Docker Image
        id: build-and-push-latest
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          context: ${{ env.CONTEXT }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
#      - name: Build and Push Latest Docker Image
#        id: build-and-push-latest
#        run: |
#          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
#          echo Creating Docker image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
#          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ${{ env.CONTEXT }}
#          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
